[package]
name = "data-structure"
version = "0.1.0"
authors = ["Locez <loki.a@live.cn>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
